# Generated by Django 3.1.2 on 2020-10-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201008_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('SF', 'San Fransisco'), ('LD', 'London'), ('GB', 'Gibraltar')], default='SF', max_length=2),
        ),
    ]
