# Generated by Django 3.1.2 on 2020-10-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('SF', 'San Francisco'), ('LD', 'London'), ('GB', 'Gibraltar')], default='SF', max_length=2),
        ),
    ]
