# Generated by Django 3.1.2 on 2020-10-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201008_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('SF', 'San Francisco'), ('LD', 'London'), ('GB', 'Gibraltar')], default='SF', max_length=2),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
