# Generated by Django 3.1.2 on 2020-10-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20201009_1722'),
        ('main_app', '0008_auto_20201009_1925'),
    ]

    operations = [
    ]
