# Generated by Django 3.1.2 on 2020-10-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20201009_1933'),
        ('main_app', '0009_auto_20201009_2031'),
    ]

    operations = [
    ]
