# Generated by Django 3.1.2 on 2020-10-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20201009_2023'),
        ('main_app', '0015_auto_20201009_2126'),
    ]

    operations = [
    ]
