# Generated by Django 3.1.2 on 2020-10-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_merge_20201009_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
    ]
